from tkinter import *
def add():
    n1 = int(number1.get())
    n2 = int(number2.get())
    result =str(n1+n2)
    answer.config(text="Answer is "+result)
def minus():
    n1 = int(number1.get())
    n2 = int(number2.get())
    result =str(n1-n2)
    answer.config(text="Answer is "+result)
def multiply():
    n1 = int(number1.get())
    n2 = int(number2.get())
    result =str(n1*n2)
    answer.config(text="Answer is "+result)
def devide():
    n1 = int(number1.get())
    n2 = int(number2.get())
    result =str(n1//n2)
    answer.config(text="Answer is "+result)
root = Tk()
root.geometry("300x300")
number1 = Entry(root)
number2 = Entry(root)
number1.pack()
number2.pack()
button = Button(root, text="Add", command= add)
button.pack()
button = Button(root, text="Minus", command= minus)
button.pack()
button = Button(root, text="Divide", command= devide)
button.pack()
button = Button(root, text="Muitiply", command= multiply)
button.pack()
answer = Label(root)
answer.pack()
root.mainloop()
